// Stable positions determine built-in lesson IDs. Never reorder existing entries.
pub const LESSONS: &[(&str, &str, i32)] = &[
    ("Home Row - Basic", "arst neio", 1),
    ("Home Row - DH Focus", "astg neio m", 1),
    ("Home Row - Common Bigrams", "th he an in er re on at en nd st es", 1),
    ("Home Row - Short Words", "star rain note nest near sent east area sane", 1),
    ("Home Row - Fluency", "the rain in spain stays mainly in the plain", 1),
    ("Top Row - Left Hand", "qwfpg arst", 2),
    ("Top Row - Right Hand", "jluy; neio", 2),
    ("Top Row - Mixed", "quick flow glad play jump wolf quay", 2),
    ("Top Row - DH Precision", "page find peak grow just long your year", 2),
    ("Top Row - Sentences", "the quick brown fox jumps over the lazy dog", 2),
    ("Bottom Row - Basic", "zxc dv kh , . /", 3),
    ("Bottom Row - Words", "dock back view size zone kind half calm", 3),
    ("Bottom Row - Integration", "every day is a new chance to learn and grow", 3),
    ("Punctuation - Basic", "hello, world! how are you today? (fine.)", 3),
    ("Punctuation - Advanced", "it's \"great\" to see you; let's start!", 3),
    ("Top 100 Words - Part 1", "the be of and a to in of it for not on with he as you do", 4),
    ("Top 100 Words - Part 2", "at this but his by from they we say her she or an will my", 4),
    ("Trigram Mastery", "the and ing her hat his tha ere for ent ion ter was", 4),
    ("Double Letters", "tell well keep book look feel seen soon moon summer", 4),
    ("Prose - Philosophy", "to be or not to be, that is the question of the soul.", 5),
    ("Prose - Technology", "artificial intelligence is the future of human computer interaction.", 5),
    ("Prose - Nature", "the mountains are calling and i must go to the peak.", 5),
    ("Numbers - Row 1", "12345 67890 54321 09876", 6),
    ("Coding - Python", "import os, sys; print(\"path:\", os.getcwd())", 6),
    ("Coding - CSS", "body { margin: 0; padding: 20px; display: flex; }", 6),
    ("Coding - HTML", "<div class=\"main\"><h1>Hello World</h1></div>", 6),
    ("Mastery - Long Text", "four score and seven years ago our fathers brought forth on this continent a new nation conceived in liberty and dedicated to the proposition that all men are created equal.", 7),
    ("Mastery - Colemak DH Stress", "bright green plants grow high above the dark deep valley below.", 7),
];
